#!/bin/bash

# Audio system
pipewire &

# Desktop and Widgets
#pcmanfm --daemon-mode &
pcmanfm --desktop &

# System tray icons
volumeicon &
clipit &
xfce4-power-manager &
blueman-applet &
(sleep 2 && conky --daemonize -c ~/.conkyrc) &

# Screensaver
xscreensaver -nosplash &

# Polkit agent (standard for Debian/XFCE environment tools)
if [ -x /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 ]; then
    /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
fi
